default: &default
  adapter: sqlite3
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: db/project_management_dev

test:
  <<: *default
  database: db/project_management_test

production:
  <<: *default
  database: db/project_management_production